Rename DataFrame columns and simplify merge
Fix the problem:

File "C:\Python\Python312\Lib\site-packages\ImPSCAD\PSCADVar.py", line 106, in PSCADVar
    df_merged = reduce(lambda left, right: pd.merge(left, right, on='time', suffixes=('_l', '_r')),    dff)


pandas.errors.MergeError: Passing 'suffixes' which cause duplicate columns {'Damping_l'} is not allowed.